Tweak home
rahulp959/vattrack.web pull request #10
Opened 2017-05-07 05:26 UTC by dhawton

Slight tweaks to CSS and change background graphic to locally hosted

2017-05-07 10:28 UTC, rahulp959 requested changes

2017-05-07 10:28 UTC, rahulp959 commented on src/Containers/Home/Home.js
> -        <div className='divrecentbox pad15'>
We should do background images from the SCSS as done before rather than adding two types of style via inline and SCSS classes

2017-05-08 03:41 UTC, dhawton commented
Splitting completed.

2017-05-08 18:30 UTC, rahulp959 approved these changes

2017-05-08 18:33 UTC, merged